version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: finance-db
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: finance-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://finance_user:finance_pass@postgres:5432/financedb
      JWT_SECRET: dev-secret-change-in-production-please
      JWT_EXPIRES_IN: 7d
      NODE_ENV: development
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: finance-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
